#!/usr/bin/perl

# PostprocessBuildPlayer #
# Grabs the plugin info from the filename after the '_'


# Dont run on any builds that are not iPhone builds
if( $ARGV[1] ne "iPhone" )
{
	exit;
}

use File::Basename;
use Foundation;


$installPath = $ARGV[0];
$currDir = `pwd`;
chomp $currDir;
$xcodeFiles = $currDir . "/Assets/Editor/Kiip";

# Error handling.
sub handler
{
	my($msg) = @_;
	`osascript -e \'tell application \"Finder\" to display dialog \"$msg\" buttons \"OK\"\'`;
	die "$msg\n";
}
$SIG{'__DIE__'}  = \&handler;


# Make sure the XcodeFiles directory exists.
opendir(XCODEPROJECTDIR, $xcodeFiles) || die("Cannot find directory $xcodeFiles");
closedir(XCODEPROJECTDIR);


# Run the builder
`python2.6 \'Assets/Editor/KiipPostProcessor.pyc\' \'$installPath\' \'$currDir\' \'Kiip\'`
